# Generated by Django 4.1.3 on 2023-01-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField(null=True)),
                ("description", models.CharField(max_length=300, null=True)),
                ("thumbnail", models.CharField(max_length=400, null=True)),
                ("color", models.CharField(max_length=200)),
                (
                    "categoryid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hi5.category",
                    ),
                ),
            ],
        ),
    ]
