# Generated by Django 3.2.5 on 2023-01-12 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(null=True)),
                ('thumbnail', models.CharField(max_length=400, null=True)),
                ('itemno', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('thumbnail2', models.CharField(max_length=500, null=True)),
                ('thumbnail3', models.CharField(max_length=500, null=True)),
                ('thumbnail4', models.CharField(max_length=500, null=True)),
                ('thumbnail5', models.CharField(max_length=500, null=True)),
                ('categoryid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hi5.category')),
            ],
        ),
        migrations.CreateModel(
            name='productdetail',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=10)),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hi5.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='hi5.product')),
            ],
        ),
    ]
