# Generated by Django 4.1.4 on 2023-01-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi5', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userid',
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categoryid',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Orderdetail',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
