# Generated by Django 4.1.3 on 2023-01-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hi5", "0002_product_size"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="color",),
        migrations.RemoveField(model_name="product", name="size",),
        migrations.CreateModel(
            name="productdetail",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("color", models.CharField(max_length=200)),
                ("size", models.CharField(max_length=10)),
                (
                    "productid",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hi5.product",
                    ),
                ),
            ],
        ),
    ]
