# Generated by Django 4.1.4 on 2023-01-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi5', '0002_alter_feedback_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
