# Generated by Django 4.1.4 on 2023-01-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi5', '0003_product_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
