# Generated by Django 4.1.4 on 2023-01-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi5', '0005_product_description_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
