# Generated by Django 4.1.4 on 2023-01-03 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hi5', '0006_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='productdetail',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=10)),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hi5.product')),
            ],
        ),
    ]
