# Generated by Django 4.1.4 on 2023-01-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi5', '0007_category_productdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
