# Generated by Django 4.1.4 on 2023-01-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi5', '0009_remove_product_description_productdetail_itemno'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='thumbnail2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='thumbnail3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='thumbnail4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='thumbnail5',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='itemno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
