# Generated by Django 4.1.4 on 2023-01-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi5', '0010_productdetail_description_productdetail_thumbnail2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='itemno',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='thumbnail2',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='thumbnail3',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='thumbnail4',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='thumbnail5',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='itemno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail5',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
