# Generated by Django 4.1.3 on 2023-01-04 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hi5", "0011_remove_productdetail_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categoryid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hi5.category",
            ),
        ),
    ]
