# Generated by Django 4.1.3 on 2023-01-02 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="account",
            fields=[
                ("userid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=12)),
                ("address", models.CharField(max_length=200)),
                ("profile_pic", models.ImageField(blank=True, null=True, upload_to="")),
                ("email", models.CharField(max_length=50)),
                (
                    "username",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
