# Generated by Django 4.1.4 on 2023-01-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userid',
            field=models.CharField(default='TK001', max_length=6, primary_key=True, serialize=False),
        ),
    ]
