# Generated by Django 4.1.4 on 2023-01-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accouts', '0004_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
