# Generated by Django 4.1.4 on 2023-01-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accouts', '0005_account_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
