# Generated by Django 4.1.4 on 2023-01-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.AutoField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
