# Generated by Django 4.1.4 on 2023-01-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
